// Generated by CoffeeScript 1.12.4
var formatType, formatTypes, getName, prependArticle, vowels;

formatType = function(type, startWithArticle) {
  var string;
  string = Array.isArray(type) ? formatTypes(type) : getName(type);
  if (startWithArticle) {
    return prependArticle(string);
  } else {
    return string;
  }
};

module.exports = formatType;

formatTypes = function(types) {
  var length, names;
  length = types.length;
  if (length === 1) {
    return getName(types[0]);
  }
  names = types.map(getName);
  if (length === 2) {
    return names.join(" or ");
  }
  names.push("or " + names.pop());
  return names.join(", ");
};

getName = function(type) {
  return type.displayName || type.name || "";
};

vowels = "aeiou";

prependArticle = function(string) {
  if (0 > vowels.indexOf(string[0].toLowerCase())) {
    return "a " + string;
  } else {
    return "an " + string;
  }
};
